repository:
  name: Arduino_Library_Template
  description: Description
  homepage: https://example.github.io/
  topics: gunce, akkoyun, arduino, library
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
labels:
  - name: Help Wanted
    color: 0e8a16
  - name: Information Needed
    color: d93f0b
  - name: Bug
    color: b60205
  - name: Feature
    color: 1d76db
branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: false
      required_linear_history: true
      restrictions: null
